import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#324053",
        "secondary-fixed": "#d5e3fc",
        "tertiary-dim": "#3c5666",
        "surface-container-lowest": "#E0E0E0",
        "surface-bright": "#D9D9D9",
        "primary-container": "#dae2fd",
        "on-error-container": "#752121",
        "tertiary": "#486272",
        "on-background": "#1A1A1A",
        "on-secondary-container": "#455367",
        "inverse-on-surface": "#9c9d9d",
        "on-surface": "#1A1A1A",
        "on-secondary": "#f8f8ff",
        "on-primary-fixed": "#373f54",
        "primary-dim": "#4a5268",
        "inverse-primary": "#dae2fd",
        "tertiary-fixed-dim": "#c2def0",
        "on-error": "#fff7f6",
        "on-tertiary-container": "#3e5868",
        "surface-variant": "#BDBDBD",
        "on-secondary-fixed-variant": "#4e5c71",
        "on-primary-container": "#4a5167",
        "secondary-container": "#d5e3fc",
        "surface-container": "#BDBDBD",
        "surface": "#C6C6C6",
        "error": "#9f403d",
        "error-dim": "#4e0309",
        "secondary-fixed-dim": "#c7d5ed",
        "on-tertiary-fixed-variant": "#486272",
        "secondary": "#526074",
        "surface-container-highest": "#B0B0B0",
        "on-surface-variant": "#333333",
        "surface-dim": "#AFAFAF",
        "on-tertiary": "#f4faff",
        "primary-fixed": "#dae2fd",
        "primary": "#1A1A1A",
        "surface-container-low": "#C6C6C6",
        "outline": "#4D4D4D",
        "primary-fixed-dim": "#ccd4ee",
        "outline-variant": "#808080",
        "tertiary-fixed": "#d0ecff",
        "surface-tint": "#1A1A1A",
        "on-primary-fixed-variant": "#535b71",
        "surface-container-high": "#BDBDBD",
        "tertiary-container": "#d0ecff",
        "on-primary": "#f7f7ff",
        "on-tertiary-fixed": "#2c4655",
        "inverse-surface": "#0c0f0f",
        "background": "#C6C6C6",
        "error-container": "#fe8983",
        "secondary-dim": "#465468"
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}

export default config
